[package]
name = "ch_01_truth_or_consequences"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
assert_cmd = "2.0.14"
pretty_assertions = "1.4.0"
